### ISSUE TITLE
Links to the built-in list of doctypes are broken in README.md 

### ISSUE THREAD

**Issue by lespacedunmatin** [cozy/cozy-settings#30]
In the README.md file, the links to the list of doctypes seems to be broken.

**Comment by clochix** [comment]
The list of document type has been removed from the documentation when we (well, actually, i) deleted the outdated developer documentation for Cozy V2. You can find it [here](https://github.com/cozy/cozy-dev-docs/commit/e77160e8c0440a30dae9496623c2286193befcb1#diff-eeb8bdec9c0eef052c0532fce07c4bacL328), but it's probably outdated, so i don't know if we should restore it into the new developer documentation.

**Comment by clochix** [comment]
@lespacedunmatin @nono just told me we have not yet started to define the doctypes for Gozy, so for now, there's no documentation for this. Sorry.

**Comment by y-lohse** [comment]
How about we remove the link, in the meantime?
