### ISSUE TITLE
Changing settings does not work on Raspbian

### ISSUE THREAD

**Issue by leolivier** [cozy/cozy-settings#66]
Hi,
On my Raspberry Pi 2/Raspbian Jessie, I can change the settings through the `cozy-stack settings` command.
When I go the settings app in my browser, I can see the changes made with `cozy-stack settings` but I cannot change the settings in the screen. It runs forever (rotating circle) and never do the change.

In the cozy errors log, I have lines like this:
`time="2017-08-25T15:35:23+02:00" level=error msg="[http] GET /settings/context Not Found(404): Context not found" domain=mydomain`
but it's on GET requests, so not sure it's related (as I said, I can see the change in the screen)...

**Comment by leolivier** [comment]
My settings are:
```
$ cozy-stack settings --domain mydomain.tld
- email: my@email
- locale: fr
- public_name: Olivier
- contaxt: beta
- context: beta
```
I just added the context to see if the error message disappears.
BTW, how do you remove an erroneous setting? I mispelled context (contaxt) and I can't remove it anymore. Is it stored in couchdb?

**Comment by y-lohse** [comment]
Hi, and thanks for the report!
Unfortunately I'm having trouble reproducing this issue, so let's try to dig a bit deeper:

- Does this affect all settings? Or are you able to change some settings but not others?
- What browser and browser version are you using?
- Are there any more errors in the console especially right *after* attempting a change?

> BTW, how do you remove an erroneous setting?

Not sure about this, maybe @nono can help us out? There's definitely a CouchDB collection for settings, and there's one that holds instance related information, so you might get lucky with one of these.

**Comment by nono** [comment]
The 404 error in the logs is not very important. It can happen and should not have an effect on changing settings via cozy-settings.

I think it is just that the `beta` context is not defined in the configuration file. You can add it if you want, like this: https://github.com/cozy/cozy-stack/blob/195278d25f0d8b83070d235402d383f65e2fa09b/cozy.example.yaml#L85-L111 (the stack needs to be restarted for the change to take effect).

> BTW, how do you remove an erroneous setting?

`cozy--stack settings contaxt:` should do the trick. And, I should update the documentation about it.

**Comment by leolivier** [comment]
@nono, thanks for the removal of the settings. It worked
@y-lohse I'm using Firefox 54 (standard version for Linux Mint 18) and it affects all settings I tested (i.e. locale, public name and email)
And I have no error in the console... 
`time=2017-08-25T17:52:14+02:00	status=200	method=PUT	host=cozy.levillain.fr.nf	uri=/settings/instance	bytes_out=264`
I just tested with Chromium and it appears to be working so a compatibility problem in Firefox?

**Comment by leolivier** [comment]
No sorry, I thought it worked in chromium but it was just because it took a fw seconds to start running... Still get the rotating circle

**Comment by y-lohse** [comment]
Mh, ok. It's very strange since the request works (code 200) and there are no errors.
Let's try to update the settings app to the latest version, just in case:

- go to your settings, and change the end of the url from `#/profile` (or whatever) to `#/install`
- repo url is `git://github.com/cozy/cozy-settings.git#build`
- slug is `settings`
- and activate the update toggle

If this doesn't help I'm afraid it might have something to do with your specific set up, which  is going to be quite hard to debug.

**Comment by leolivier** [comment]
Thanks @y-lohse: It worked! 
So there probably was a bug which has been corrected (without even knowing it :) :+1:

**Comment by y-lohse** [comment]
Great!
