### ISSUE TITLE
Pourquoi ne pas utiliser cozy-client-js ?

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-settings#74]
https://github.com/cozy/cozy-settings/blob/d0268b29e322dfceedaaa5cb9f631c2647269381/src/actions/index.js#L203

Pourquoi ne pas utiliser cozy-client-js ici ? Je vois que dans cozy-client-js il y a une méthode `getInstance` et `updateInstance` qui devrait couvrir les besoins pour modifier les settings. Je n'ai pas réussi à utiliser `updateInstance` mais la méthode avec `cozyFetch` a marché, je pense donc que `updateInstance` n'est plus bon sur cozy-client-js et qu'il faut backporter cette méthode.

**Comment by gregorylegarec** [comment]
Moved to https://github.com/cozy/cozy-client-js/issues/212
